
services:
  - type: web
    name: seu-nome-do-serviço
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn --bind 0.0.0.0:$PORT app:app"
    port: 5000  # Esta é a porta padrão que você definiu no seu código
